---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    tier: backend
data:
  config : |
    server {
      listen 8080;
      }
      location /api {
        # URI routing
        location /api/app1 {
            proxy_pass http://app1:8080;
        }
        location /api/app2 {
            proxy_pass http://app2:8080;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels:
    app: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      volume:
      - name: dir
        hostpath:
          path: /src
      - name: config
        configMap:
          name: nginx-config
          key: config
      containers:
      - name: nginx-app
        image: docker-io/nginx:latest
        volumeMounts:
          - name: dir
            mountPath: /src
          - name: config
            mountPath: /etc/nginx/conf.d
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-app
spec:
  ports:
  - name: nginx-app
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    tier: backend
    app: nginx
  type: LoadBalancer
