---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app2
  name: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node2
  strategy: {}
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: docker.io/azizctg08/app2:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app2
  name: app2
spec:
  ports:
  - name: app2
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32500