pipeline{
    agent{
        label "PHP"
    }
    stages{
        stage("Deploy app2"){
            steps{
                sh '''
                    kubectl namespace bs-app
                    kubectl create -f ./deploy/deploy.yaml
            }
        }
    }
}
